extends Node

signal hover_target_changed(target: Node)
signal interaction_menu_requested(target: Node, screen_position: Vector2)
signal interaction_action_requested(target: Node, action_id: StringName)
signal interaction_pointer_capture_changed(is_captured: bool)
signal interaction_ui_cancel_requested()
signal interaction_targeting_started(source: Node, action_id: StringName)
signal interaction_targeting_cancelled(source: Node, action_id: StringName)
signal interaction_targeting_failed(source: Node, target: Node, action_id: StringName, reason: StringName, details: Dictionary)
signal move_requested(actor: Node, actor_data: Resource, destination_data: Resource)
signal movement_started(actor: Node, path: PackedVector3Array)
signal movement_step_reached(actor: Node, destination_data: Resource)
signal movement_completed(actor: Node, destination_data: Resource)
signal movement_failed(actor: Node, destination_data: Resource, reason: StringName)
signal examined_output(target_domain: StringName, target_data: Resource, output: Dictionary)
signal editor_mode_changed(mode: StringName)
signal editor_selection_changed(selected_node: Node, selected_data: Resource, selected_kind: StringName)
signal editor_map_loaded(map_data: Resource, path: String)
signal editor_map_saved(map_data: Resource, path: String)
